---
# Source: oes/templates/services/oes-ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: ui
    heritage: "Helm"
    release: "oes"
    chart: "oes-4.0.21"
  name: oes-ui
spec:
  type: LoadBalancer
  ports:
  - name: "https"
    port: 443
    targetPort: 8080
  - name: "http"
    port: 8080
    targetPort: 8080
  - name: "lbhttp"
    port: 80
    targetPort: 8080
    nodePort: 
  selector:
    app: oes
    component: ui
