---
# Source: oes/charts/spinnaker/templates/rbac/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oes-spinnaker-halyard
  labels:
    app: "oes-spinnaker"
    heritage: "Helm"
    release: "oes"
    chart: "spinnaker-2.2.3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role                 # ClusterRole, if we have access to cluster resources
  name: spinnaker-role       # edit, if we have the access
subjects:
- namespace: oes
  kind: ServiceAccount
  name: oes-spinnaker-halyard
