apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-oes-spin
spec:
  acme:
    email: hanumesh.kumar@opsmx.io
    preferredChain: ""
    privateKeySecretRef:
      name: demo-authtls
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
