k8sServiceType: LoadBalancer

# Global variables can be accessed across all the charts including sub-charts
global:

  ssl:
    enabled: false

  certManager:
    installed: true

  # Common gate for both spin and oes services. Change ONLY if required
  commonGate:
    spinnakerRBAC: true  # Set to true if RBAC is enabled in Spinnaker

  ## Set to true to expose oes-ui, oes-gate services over ingress
  createIngress: false

  ## Set to false only if user uses gitops style and user dont want the repo to be created automatically in github.com
  githubcreationHook: false

  gitea:
    enabled: false

  # Spinnaker Deck URL configuration; url overwhich spinnaker deck will be accessed
  spinDeck:
    protocol: https
    host: spindeck.wurm.opsmx.net
    #port: 31464

    ingress:
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: deck-authtls

  spinGate:
    protocol: https
    host: spingate.wurm.opsmx.net
    #port: 31465

    ingress:
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: gate-authtls

  oesUI:
    protocol: https
    host: oesui.wurm.opsmx.net
    # Use below port when hostname above is an external IP instead of a hostname
    #port: 31466

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: oes-ui-authtls

  ## OES-Gate url configuration
  oesGate:
    protocol: https
    host: oesgate.wurm.opsmx.net
    
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: oes-gate-authtls

  # Set it to false if own LDAP is to be configured
  installOpenLdap: false

  auth:
    saml: true

  ldap:
    enabled: false

  spinnakerUrl: true
  saporgate:
    config:
      username: anoop@opsmx.io       #Name of the valid user in your service provider
      adminGroups: admin,OpsMx-DevOps    #Name of the valid admin group in your service provider
      password: encrypted:saporpassword:saporpassword  #password for the saporgate

  sapor:
    config:
      encrypt:
        enabled: true
        key: Q7udUkHPuA3VnNlOtksSgQ
  ###############################################################################
  minio:
    enabled: false

###############################################################################
db:
  enabled: false
  url: jdbc:postgresql://database-1.cluster-cyjw4hmntwfy.us-east-1.rds.amazonaws.com:5432
  username: postgres
  password: encrypted:dbpassword:dbpassword

###############################################################################
gate:
  config:
    saml:
      enabled: true
      keyStore: /opt/spinnaker/saml/oessaml.jks  # The key in this secret must be oessaml.jks
      keyStorePassword: encrypted:keystorepassword:keystorepassword
      metadataUrl: /opt/spinnaker/saml/oesmetadata.xml # The key in this secret must be oesmetadata.xml
      redirectProtocol: https
      redirectHostname: oesui.wurm.opsmx.net/gate  # OES gate host name
      issuerId: oeswurm
      jksSecretName: oessamljks
      metadataSecretName: oesmetadataxml

#####################################################
# Spinnaker instance configuration
#####################################################
spinnaker:
  autoInstallSampleApps: false   # Set this to FALSE if upgrading
  # Initialize gitOps style Halyard
  gitopsHalyard:
    enabled: true
    secretName: opsmx-gitops-auth  # No need to change this
    repo:
      type: git # git, s3, stash(bitbucket server) use a different sample values file for s3/bitbuck-stash
      configArgs: "http.sslVerify=false"
      ## Configure below fields only if repo type is git/stash. Skip to s3 section if type is s3
      baseUrlHostName: github.com    # Specify the Base FQDN of your repository without the protocol
      organization: OpsMx
      repository: WU-RM-Repo # repo name for GitOps Halyard (Sample Reference: https://github.com/OpsMx/sample-gitops-repo.git).
      halConfigBranch: master # Branch under which halyard config is present under above repository
      halConfigPath: / #relative path from repository root folder
      dynamicAccRepository: WU-RM-Repo # Please provide the repo name of the GitOps Dynamic Accounts Directory. Can be same as Hal repo. 
      dynAccntConfigPath: dynaccount/ #relative path from repository root folder
      username: hanumeshc  # Username to authenticate with git/stash repo
      token: encrypted:gittoken:gittoken  # Token corresponding to above username
       ## Configure below fields only if repo type is s3
    # Promote applications and pipelines from one environment to another or take backup
    pipelinePromotion:  # GitHub only,  Not supportd on S3 or Stash
      enabled: true
      type: git  # git, s3, stash
      organization: OpsMx  # Also called "project" in some repos
      repository: WU-RM-Repo  # bucket name in case of S3
      rootFolder: pipeline/
      baseUrl: github.com  #  "git_url"
      username: hanumeshc
      token: encrypted:gittoken:gittoken
      branch: master
      usermail: anoop@opsmx.io

  spinCli:
    auth:
      basic:
        username: anoop@opsmx.io          # Use credentials corresponding to spinCli.gate.endpoint
        password: encrypted:saporpassword:saporpassword

rabbitmq:
  username: rabbitmq
  password: encrypted:rabbitmqpassword:rabbitmqpassword
#####################################################
redis:
  url: redis://:encrypted:redispassword:redispassword@{{ .Release.Name }}-redis-master
  password: encrypted:redispassword:redispassword

forwarder:
  externalName: wurm-controller.opsmx.net
