---
# Source: oes/templates/secrets/oes-platform-configmap.yaml
apiVersion: v1
stringData:
  platform-local.yml: |
    
    spring:
      datasource:
        url: jdbc:postgresql://database-1.cluster-cyjw4hmntwfy.us-east-1.rds.amazonaws.com:5432/platformdb
        username: 'postgres'
        password: 'encrypted:dbpassword:dbpassword'
    ldap.managerPassword: 'opsmxadmin123'
    redis:
        connection: redis://:encrypted:redispassword:redispassword@oes-redis-master:6379
    #datasource.url: jdbc:postgresql://database-1.cluster-cyjw4hmntwfy.us-east-1.rds.amazonaws.com:5432/visibilitydb
    #postgres.password: 'encrypted:dbpassword:dbpassword'
    #postgres.username: 'postgres'
    
    datasource:
      secretManagement:
        source: db
    rbacEnabled: true
    supportedFeatures:
      - deployment_verification
      - sapor
      - visibility
    userGroup:
      superAdminGroups: admin,OpsMx-DevOps
    user:
      source: gate
    ldap:
      enabled: false
      url: ldap://oes-openldap:389
      managerDn: cn=admin,dc=example,dc=org
      groupSearchBase: ou=groups,dc=example,dc=org
      groupSearchFilter: member={0}
      groupRoleAttributes: cn
      userDnPattern: cn={0},dc=example,dc=org
    dashboard:
      scheduler:
        enable: false
        fixedDelay:
          in:
            milliseconds: 120000
        initialDelay:
          in:
            milliseconds: 300000
        workerThreads: 50
    database:
      cleanup:
        scheduler:
          enabled: false
          daysInterval: 180
          cron: 0 0 0 * * *
    oes:
      sapor:
        url: http://oes-sapor:8085
      autopilot:
        url: http://oes-autopilot:8090
      dashboard:
        url: http://oes-dashboard:8094
      visibility:
        url: http://oes-visibility:8096
      auditclient:
        url: http://oes-audit-client:8098
      policyGate:
        url: http://oes-gate:8084
        path: /v1/data/
      auditservice:
        url: "http://oes-audit-service:8097"
      ui:
      # Ex: "https://oes-poc.dev.opsmx.org/"
        url: "https://oesui.wurm.opsmx.net/ui"
      gate:
        url: http://oes-gate:8084
      approvalGate:
        apiUrl: http://oes-gate:8084/visibilityservice/v5/approvalGates/{id}/trigger
    
      verificationGate:
        apiUrl: http://oes-gate:8084/autopilot/api/v3/registerCanary
    
    logging:
      level:
        com.opsmx.platformservice: INFO
        org.springframework.security: INFO
        org.springframework.web: INFO
    
    standardErrorCodes:
      filePath: /opsmx/conf/standard-error-code.csv
    
kind: Secret
metadata:
  name: oes-platform-config
  labels:
    app: oes
    component: platform
    heritage: "Helm"
    release: "oes"
    chart: "oes-4.0.21"
