---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://hanumeshc:encrypted%3Agittoken%3Agittoken@github.com/OpsMx/WU-RM-Repo.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/OpsMx/WU-RM-Repo.git
  gituser: hanumeshc
  gittoken: encrypted:gittoken:gittoken
  dynamicAccRepository: WU-RM-Repo

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
