apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(vDfFwsjBrqAD2+EYsPCBa6xe8aggK//N)
        username: anoop@opsmx.io
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: local-spin-cli-config
