apiVersion: v1
kind: Service
metadata:
  labels:
    app: albertsons-dinghy
    component: dinghy
  name: dinghy
spec:
  ports:
  - name: dinghy-service
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: albertsons-dinghy
    component: dinghy
  sessionAffinity: None
  type: ClusterIP
