apiVersion: v1
stringData:
  JIRA_USERNAME: jayasree@opsmx.io
  JIRA_URL: https://devopsmx.atlassian.net
  JIRA_TOKEN: ENC(GouUOJ3TJhbmcTOaC2FsBLe2qcL5T/j+HT1tAkftWDTcX4gAg6riFQ==)
kind: Secret
metadata:
  name: jira-secret
type: Opaque
