---
# Source: oes/charts/spinnaker/templates/secrets/spin-config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: oes-spinnaker-spin-config
  labels:
    app: "oes-spinnaker"
    heritage: "Helm"
    release: "oes"
    chart: "spinnaker-2.2.3"
stringData:
  config: |
    auth:
      basic:
        password: encrypted:saporpassword:saporpassword
        username: anoop@opsmx.io
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
